(library
  (name PI)
  (modules PI)
  (libraries zarith)) 

(include_subdirs qualified)

(executable
 (name Arquimedes)
 (modules Arquimedes)
 (libraries zarith PI))

(executable
 (name Liu_Hui)
 (modules Liu_Hui)
 (libraries zarith PI))

(executable
 (name Zu_Chongzhi)
 (modules Zu_Chongzhi)
 (libraries zarith PI))

(executable
 (name Al_Kashi)
 (modules Al_Kashi)
 (libraries zarith PI))

(executable
 (name Ludolph_Van_Ceulen)
 (modules Ludolph_Van_Ceulen)
 (libraries zarith PI))

(executable
 (name Jonh_Machin)
 (modules Jonh_Machin)
 (libraries zarith PI))

(executable
 (name Madhava)
 (modules Madhava)
 (libraries zarith PI))

(executable
 (name Snell)
 (modules Snell)
 (libraries zarith PI))

(executable
 (name Jurij_Vega)
 (modules Jurij_Vega)
 (libraries zarith PI))

(executable
 (name Zacharias_Dase)
 (modules Zacharias_Dase)
 (libraries zarith PI))

(executable
 (name William_Shanks)
 (modules William_Shanks)
 (libraries zarith PI))

(executable
 (name William_Rutherford)
 (modules William_Rutherford)
 (libraries zarith PI))

(executable
 (name Abraham_Sharp)
 (modules Abraham_Sharp)
 (libraries zarith PI))


(executable
 (name D_F_Ferguson)
 (modules D_F_Ferguson)
 (libraries zarith PI))


(executable
 (name Thomas_Clausen)
 (modules Thomas_Clausen)
 (libraries zarith PI))


(executable
 (name BBP)
 (modules BBP)
 (libraries zarith PI))


(executable
 (name BBP_no_zarith)
 (modules BBP_no_zarith)
 (libraries zarith PI))


(executable
 (name Monte_Carlo)
 (modules Monte_Carlo)
 (libraries zarith PI))


(executable
 (name Chudnovsky)
 (modules Chudnovsky)
 (libraries zarith PI))